/** home-screen dictionary; en defines the key set, vi must match (type-checked) */
export const strings = {
  en: {
  "addFolderRoot": "Add folder…",
  "removeFolderRoot": "Remove from list",
  "rootUnavailable": "Not available",
  "navRecent": "Recent",
  "navStarred": "Starred",
  "navCloud": "Cloud Projects",
  "cloudSubtitle": "Projects created on the web. Editing continues in your browser — click any project to open it.",
  "cloudSearchPlaceholder": "Search {n} projects…",
  "cloudNoResults": "No matching projects.",
  "cloudGroupThisWeek": "This week",
  "cloudGroupThisMonth": "Earlier this month",
  "cloudSortLabel": "Sort: {v}",
  "cloudSortRecent": "Recent",
  "cloudSortOldest": "Oldest",
  "cloudRefresh": "Refresh",
  "cloudLoginHint": "Sign in to your account to see projects you created on the web.",
  "cloudEmpty": "No web projects yet.",
  "cloudError": "Failed to load. Try again later.",
  "cloudRetry": "Retry",
  "cloudLoadMore": "Load more",
  "cloudOpenInBrowser": "Open in browser",
  "navTrash": "Trash",
  "navTrashTip": "Deleted files go to the system Trash and can be restored there",
  "secQuickStart": "Quick start",
  "secRecent": "Recent",
  "secStarred": "Starred",
  "secActivity": "Activity",
  "colName": "Name",
  "colLocation": "Location",
  "colModified": "Modified",
  "colSize": "Size",
  "newDoc": "AI Docs",
  "newSheet": "AI Sheets",
  "newSlide": "AI Slides",
  "newMarkdown": "AI Markdown",
  "newHtml": "AI HTML",
  "newPdf": "AI PDF",
  "openLocal": "Open Local File",
  "dropToOpenTitle": "Drop to open",
  "greetMorning": "Good morning",
  "greetAfternoon": "Good afternoon",
  "greetEvening": "Good evening",
  "greetAsk1": "What would you like to create today?",
  "greetAsk2": "Ready to get started?",
  "greetAsk3": "What are you working on?",
  "greetAsk4": "Where shall we begin today?",
  "greetAsk5": "Feeling creative?",
  "greetAsk6": "What's next on your mind?",
  "filterAll": "All",
  "filterDocs": "Docs",
  "filterSheets": "Sheets",
  "filterSlides": "Slides",
  "filterPdf": "PDF",
  "filterMd": "Markdown",
  "filterHtml": "HTML",
  "filterAria": "Filter by type",
  "fileCount": "{n} files",
  "fileCountOne": "{n} file",
  "selectedCount": "{n} selected",
  "selectAll": "Select all",
  "selectFile": "Select {name}",
  "removeFromList": "Remove from list",
  "missingFileTitle": "File unavailable",
  "missingFileBody": "“{name}” can’t be found. It may be on a disconnected drive, or it was moved or deleted. Remove it from the list?",
  "deleteFiles": "Delete files",
  "cancel": "Cancel",
  "star": "Star",
  "unstar": "Unstar",
  "moreActions": "More actions",
  "open": "Open",
  "revealInFolder": "Reveal in folder",
  "copyPath": "Copy path",
  "rename": "Rename",
  "duplicate": "Duplicate",
  "renameFailed": "Rename failed",
  "emptyStarred": "No starred files — hover a row and click the star.",
  "emptyRecent": "No recent files — create or open a file to get started.",
  "emptyFiltered": "No files of this type.",
  "folders": "Folders",
  "newFolder": "New folder",
  "newSubfolder": "New subfolder",
  "untitledFolder": "Untitled folder",
  "folderType": "Folder",
  "moveToFolder": "Move to folder…",
  "moveToFolderTitle": "Move to folder",
  "searchFolders": "Search folders",
  "searchFilesPlaceholder": "Search file names and contents…",
  "searchIndexing": "Indexing {n} files…",
  "searchNoResults": "No files match “{q}”",
  "searchResultCount": "{n} results",
  "searchResultCountOne": "{n} result",
  "searchClear": "Clear search",
  "noMatchingFolders": "No matching folders.",
  "currentFolder": "Current",
  "moveCount": "Move {n}",
  "itemCount": "{n} items",
  "itemCountOne": "{n} item",
  "emptyFolder": "This folder is empty. Create a file, or drag files here.",
  "deleteFolder": "Delete folder…",
  "deleteFolderTitle": "Delete folder?",
  "deleteFolderConfirm": "\"{name}\" and everything inside it will be moved to the trash.",
  "folderMoreActions": "More actions for {name}",
  "conflictTitle": "An item with that name already exists",
  "conflictBodyOne": "The target folder already contains \"{name}\". What would you like to do?",
  "conflictBodyMany": "The target folder already contains {n} items with the same names. What would you like to do?",
  "conflictKeepBoth": "Keep both",
  "conflictReplace": "Replace",
  "rootUnusable": "The default save location is unavailable, so folders cannot be shown.",
  "pickSaveDir": "Choose a save location",
  "deleteModalTitle": "Delete Files",
  "deleteConfirmOne": "Move \"{name}\" to the Trash?",
  "deleteConfirmMany": "Move these {n} files to the Trash?",
  "deleteMoreCount": "… {n} in total",
  "delete": "Delete",
  "timelineEmpty": "No AI conversations in this project yet.",
  "timelineYou": "You",
  "timelineUserAria": "User",
  "untitled": "Untitled",
  "noContent": "(empty)",
  "accountGenspark": "Account",
  "account": "Account",
  "login": "Sign in",
  "loginGenspark": "Sign in",
  "loggedIn": "Signed in",
  "loggedInGenspark": "Signed in",
  "waitingLogin": "Waiting for browser sign-in… Click to relaunch the sign-in page",
  "loginTimeout": "Sign-in timed out — click to retry",
  "loginLaunchFailed": "Could not start sign-in — click to retry",
  "loginOpenManually": "Browser did not open? Click to open manually",
  "loginOpenShort": "Open sign-in page manually",
  "loginCopyUrl": "Copy sign-in link",
  "loginCopied": "Copied",
  "loginNetworkError": "Cannot reach server — check your network or proxy settings",
  "loginExpired": "Sign-in expired — click to retry",
  "loginFailed": "Sign-in failed — click to retry",
  "waitingShort": "Waiting…",
  "loggingOut": "Signing out…",
  "logout": "Sign out",
  "credits": "Credits",
  "creditsTip": "View credit usage details",
  "appVersion": "Version {v}",
  "versionLabel": "Version",
  "updateChannel": "Update Channel",
  "channelStable": "Stable",
  "channelBeta": "Beta",
  "theme": "Theme",
  "themeLight": "Light",
  "themeDark": "Dark",
  "themeSystem": "Follow System",
  "saveLocation": "Save Location",
  "setAutoSave": "Auto-save all documents",
  "setAutoSaveDesc": "Turn on AutoSave by default in every editor. You can still switch it off for a single window.",
  "setAnalytics": "Send anonymous usage statistics",
  "setAnalyticsDesc": "Enabled by default and can be turned off anytime in Settings → General. Uses Google Analytics 4; Google receives your public IP address and transport metadata, but document contents and file names are never collected.",
  "setSearchRerank": "Jev search reranking",
  "setSearchRerankDesc": "Sends the top 20 local hits' excerpts to TypeSafe's Jev model and reorders them by relevance. Off by default; when on, excerpts leave this device.",
  "setSearchRerankEndpoint": "Jev endpoint",
  "searchRerankedBy": "Reordered by relevance with Jev",
  "searchJevSettings": "Jev semantic reranking",
  "setAiPanelSide": "AI sidebar position",
  "aiPanelSideLeft": "Left",
  "aiPanelSideRight": "Right",
  "setAiFontSize": "AI panel text size",
  "aiFontSizeDefault": "Default",
  "aiFontSizeLarge": "Large",
  "aiFontSizeXLarge": "Extra large",
  "aiFontSizeCustom": "Custom",
  "setAiSpellcheck": "Spell check in AI chat",
  "setDefaultApp": "Default app for Office documents",
  "setDefaultAppDesc": "Open .docx, .xlsx and .pptx files in Xiao Office when double-clicked.",
  "setDefaultAppIs": "Xiao Office is already the default.",
  "setDefaultAppOther": "Current default: {app}",
  "setDefaultAppSet": "Make default",
  "setDefaultAppOpenSettings": "Open system settings",
  "setDefaultAppFailed": "Could not change it. Please set it in the system settings.",
  "setAiSpellcheckDesc": "Underline misspelled words while typing in the AI chat input.",
  "settings": "Settings",
  "setSecAccount": "Account",
  "setSecGeneral": "General",
  "setMcp": "Local MCP server",
  "setMcpDesc": "Let external AI agents (Claude Desktop, Cursor…) create Word documents through this running app. Localhost only.",
  "setMcpPort": "Port",
  "setMcpRunning": "Running",
  "setMcpStopped": "Not running",
  "setMcpConn": "Connection",
  "setMcpUrlHttp": "Streamable HTTP (recommended)",
  "setMcpUrlSse": "SSE (legacy clients)",
  "setMcpCopy": "Copy",
  "setMcpCopied": "Copied",
  "setMcpConfig": "Client configuration example",
  "setMcpConfigDesc": "Add this to the MCP server config of a client (the mcp.json of Claude Desktop, the MCP settings of Cursor, …).",
  "setMcpBg": "Background generation",
  "setMcpBgDesc": "Write documents straight to a path without opening the UI; when off, generation happens visibly in the app.",
  "setMcpLog": "Logging",
  "setMcpLogDesc": "Record MCP server and tool activity to a local log file",
  "setMcpLogFile": "Log file",
  "setMcpLogOpen": "Open",
  "setMcpLogClear": "Clear",
  "setMcpHealth": "Health check",
  "setMcpLogRefresh": "Refresh",
  "setMcpLogEmpty": "No log entries yet",
  "setSecAbout": "About",
  "setSecIntegrations": "Integrations",
  "intgHeroTitle": "Use Xiao Office from your AI assistant",
  "intgHeroDesc": "Once connected, Claude Code, Codex, Cursor, Claude Desktop and similar assistants can create, convert, read and edit Word, Excel, PowerPoint, PDF and Markdown files for you. Everything runs on this computer; nothing is uploaded.",
  "intgHeroStep1": "Pick a route: CLI if your assistant can run terminal commands, MCP if it cannot",
  "intgHeroStep2": "Follow that section below; usually a single click",
  "intgHeroStep3": "Start a new chat and just ask",
  "intgStep1Title": "Install the skill into your assistant",
  "intgStep1Desc": "Only assistants found on this computer are listed. Install into the one you actually use; you do not need all of them.",
  "intgStep1Update": "When a Xiao Office update ships a newer skill, an Update button appears next to that assistant.",
  "intgSkillVersion": "skill {v}",
  "intgStateMissing": "Skill not installed",
  "intgStateInstalled": "Skill {v} installed · ready in your next chat",
  "intgOtherToggle": "My assistant is not listed",
  "intgOtherDesc": "Pick any one of these three ways. They all install the same skill, so there is no need to do more than one.",
  "intgOtherFolderTitle": "Any assistant that reads SKILL.md folders",
  "intgOtherFolderDesc": "Pick its skills folder and Xiao Office writes the file there.",
  "intgOtherZipTitle": "Hand the file to the assistant",
  "intgOtherZipDesc": "Save the skill as a zip, then ask the assistant to install it.",
  "intgOtherNpxTitle": "With the skills command (needs Node.js)",
  "intgOtherNpxDesc": "Run this in a terminal:",
  "intgCopy": "Copy",
  "intgStep2Title": "Try it",
  "intgStep2Desc": "Open a new chat in your assistant and ask in plain words, for example:",
  "intgStep2DescBefore": "Once installed, open a new chat in your assistant and ask in plain words, for example:",
  "intgExample1": "Turn ~/Downloads/report.md into a Word document",
  "intgExample2": "Make a 6-slide deck about our Q3 results",
  "intgExample3": "Convert budget.xlsx to PDF and open it in Xiao Office",
  "intgStep2Note": "The assistant runs the genoffice command line itself; you never have to type it.",
  "intgCliPartTitle": "CLI · command line + skill",
  "intgCliPartDesc": "For assistants that can run terminal commands (Claude Code, Codex, Cursor and others). Once the skill is installed, the assistant calls the genoffice command line itself to create, convert, read and edit files; you never type a command.",
  "intgMcpPartTitle": "MCP",
  "intgMcpPartDesc": "MCP is the common protocol AI assistants use to call external tools. Use it when your assistant cannot run commands (Claude Desktop, for example) or when you want it to drive the Xiao Office window directly. Pick either of the two ways below.",
  "intgMcpStdioTitle": "Started by the assistant (recommended)",
  "intgMcpStdioDesc": "The assistant launches genoffice mcp itself: nothing to switch on here, and Xiao Office does not need to be open. Same features as the CLI.",
  "intgMcpHttpTitle": "Local HTTP server",
  "intgMcpHttpDesc": "Runs inside Xiao Office; the assistant connects to a URL and you can watch it build the document step by step in the Word editor. Xiao Office must stay open; Word documents only for now.",
  "intgMcpHttpAdvanced": "Advanced: other endpoints and log",
  "intgMcpTryNote": "The assistant calls Xiao Office through MCP; you never type a command.",
  "intgMcpClaudeTitle": "Claude Code",
  "intgMcpClaudeDesc": "Run this once in a terminal:",
  "intgMcpOtherTitle": "Cursor, Claude Desktop or any other MCP-capable assistant",
  "intgMcpOtherDesc": "Add this to its MCP server settings (a JSON file, or \"Add MCP server\" in its settings):",
  "intgMcpNote": "The skill and MCP can be set up side by side; the assistant picks one. They do exactly the same things.",
  "intgCliTitle": "Advanced: genoffice command line",
  "intgCliReady": "genoffice {v} · ready in your terminal ({path})",
  "intgCliNotOnPath": "genoffice {v} · not on your terminal's PATH. Assistants still find it through ~/.genoffice/launcher, so the skill works. To type genoffice yourself, run this once:",
  "intgCliLauncher": "Launcher folder",
  "intgStateOutdated": "Installed {v}, update to {next} available",
  "intgStateModified": "Installed {v} (modified)",
  "intgStateForeign": "Installed {v} (not by this app)",
  "intgStateNewer": "Installed {v} (newer than the bundled one)",
  "intgStateOccupied": "Folder already in use",
  "intgInstall": "Install",
  "intgUpdate": "Update",
  "intgUninstall": "Uninstall",
  "intgReinstall": "Reinstall as {v}",
  "intgOverwrite": "Overwrite",
  "intgConfirm": "Confirm",
  "intgConfirmWrite": "Will write: {path}",
  "intgConfirmRemove": "Will delete: {path}",
  "intgConfirmOverwriteModified": "Your edits to that file will be overwritten.",
  "intgConfirmOverwriteOccupied": "The existing SKILL.md in that folder will be replaced.",
  "intgInstalledHint": "Installed. Takes effect in a new session.",
  "intgInstallElsewhere": "Install into another folder…",
  "intgPickDirTitle": "Choose a skills folder",
  "intgDownloadZip": "Download skill (zip)",
  "intgSaveZipTitle": "Save skill",
  "intgSavedTo": "Saved to {path}",
  "intgCopied": "Copied",
  "intgCliEphemeral": "Drag Xiao Office into Applications first, then use the command line.",
  "intgCopyPath": "Copy path",
  "intgCliNeedsUpdate": "This skill needs command line {v} or newer; update Xiao Office.",
  "intgLoading": "Checking…",
  "intgUpdateDue": "Skill update available",
  "setSecAiModel": "AI Model",
  "setAiProvider": "Provider",
  "setAiModelId": "Model",
  "setAiApiKey": "API Key",
  "setAiKeyHint": "Stored only on this device.",
  "setAiBaseUrl": "Base URL",
  "setAiBaseUrlHint": "Leave empty for the official endpoint.",
  "setAiGensparkHint": "Uses your cloud sign-in; no API key needed.",
  "setAiCodexPath": "Codex executable",
  "setAiCodexPathHint": "Only set this for a custom install; leave blank to auto-detect.",
  "setAiCodexAutoPlaceholder": "Auto-detect (recommended)",
  "setAiCodexHint": "Automatically finds the current signed-in Codex CLI after updates; a custom path is optional. No API key is needed.",
  "setAiByokNote": "Chats use your own key. Image generation and media analysis follow the AI Media section; web search uses configured or free sources.",
  "setAiSave": "Save",
  "setAiSaved": "Saved",
  "setAiTest": "Test connection",
  "setAiTesting": "Testing…",
  "setAiTestOk": "Connection OK",
  "setAiTestFail": "Connection failed",
  "setAiMaxTokens": "Max output tokens",
  "setAiMaxTokensDesc": "Output budget for one turn. Reasoning models spend part of it thinking, so an answer can come back empty once the budget runs out; raise this value if that happens.",
  "setSecAiMedia": "AI Media & Search",
  "setAiMediaGensparkHint": "Image generation and image/video analysis use cloud AI services.",
  "setAiImageModel": "Image model",
  "setAiAnalysisModel": "Analysis model",
  "setAiSearchGensparkHint": "Web and image search use configured search engines or free sources.",
  "setAiSearchSerperHint": "Serper serves both web and image search with your key.",
  "setAiSearchTavilyHint": "Tavily serves web search with your key; image search falls back to free sources.",
  "setAiSearchParallelHint": "Leave the key blank for free Parallel search (limited usage). Add a key to use your Parallel account. Image search uses other sources.",
  "setAiCapImage": "Image generation",
  "setAiCapAnalysis": "Image analysis",
  "setAiCapVideo": "Video analysis",
  "setAiCapSearch": "Web search",
  "setAiCapFileSearch": "Local file search",
  "setAiSharedKeyHint": "A vendor's key and base URL are shared across capabilities; enter them once.",
  "setAiGskTools": "Cloud extension tools",
  "setAiGskToolsDesc": "Web search, image generation and media analysis run through cloud tools; when off, free sources are used.",
  "setGithub": "Open Source",
  "starOnGitHub": "Star on GitHub",
  "starPromptTitle": "Enjoying Xiao Office?",
  "starPromptTitleN": "You've opened {n} documents with Xiao Office",
  "starPromptBody": "Xiao Office is free and open source. A star on GitHub is the best way to support the team.",
  "starPromptGo": "Star on GitHub",
  "starPromptDone": "Already starred",
  "starPromptLater": "Maybe later",
  "onbStarHint": "If you like Xiao Office, give us a star on GitHub.",
  "setEmail": "Email",
  "setNotLoggedIn": "Not signed in",
  "setViewUsage": "View usage",
  "setChange": "Change",
  "today": "Today",
  "yesterday": "Yesterday",
  "daysAgo": "{n}d ago",
  "language": "Language",
  "closeTab": "Close tab",
  "tabList": "All tabs",
  "appMenu": "Menu",
  "newTab": "New tab",
  "onbTitle1": "Welcome to Xiao Office",
  "onbSubtitle1": "The first open-source, AI-native office suite",
  "onbBody1": "Create docs, build sheets, make slides, and review PDFs. AI is built into every step.",
  "onbTitle2": "This is just the beginning",
  "onbBody2": "Xiao Office is still in alpha. Join the group chat on GenTeam to share feedback and help shape what comes next.",
  "onbCredits": "Supports powerful AI models including Gemini, Claude, GPT, and DeepSeek",
  "onbJoinGenTeam": "Join GenTeam",
  "onbSkip": "Skip",
  "onbNext": "Next",
  "onbStart": "Get started",
  "onbStepAria": "Page {n} of {total}",
  "onbTitle3": "Free for everyone",
  "onbBody3": "No license fees. No ads. No watermarks.",
  "onbNote3": "AI features run seamlessly with your API key or local models.",
  "onbBack": "Back"
},
  vi: {
  "addFolderRoot": "Thêm thư mục…",
  "removeFolderRoot": "Xóa khỏi danh sách",
  "rootUnavailable": "Không khả dụng",
  "navRecent": "Gần đây",
  "navStarred": "Đã gắn dấu sao",
  "navCloud": "Dự án đám mây",
  "cloudSubtitle": "Các dự án được tạo trên web. Tiếp tục chỉnh sửa trên trình duyệt — nhấp vào bất kỳ dự án nào để mở.",
  "cloudSearchPlaceholder": "Tìm kiếm trong {n} dự án…",
  "cloudNoResults": "Không tìm thấy dự án phù hợp.",
  "cloudGroupThisWeek": "Tuần này",
  "cloudGroupThisMonth": "Tháng này",
  "cloudSortLabel": "Sắp xếp: {v}",
  "cloudSortRecent": "Mới nhất",
  "cloudSortOldest": "Cũ nhất",
  "cloudRefresh": "Làm mới",
  "cloudLoginHint": "Đăng nhập tài khoản để xem các dự án tạo trên web.",
  "cloudEmpty": "Chưa có dự án nào trên web.",
  "cloudError": "Tải thất bại, vui lòng thử lại sau.",
  "cloudRetry": "Thử lại",
  "cloudLoadMore": "Tải thêm",
  "cloudOpenInBrowser": "Mở trong trình duyệt",
  "navTrash": "Thùng rác",
  "navTrashTip": "Các tệp đã xóa nằm trong Thùng rác hệ thống, có thể khôi phục từ đó",
  "secQuickStart": "Bắt đầu nhanh",
  "secRecent": "Đã dùng gần đây",
  "secStarred": "Đã gắn dấu sao",
  "secActivity": "Hoạt động dự án",
  "colName": "Tên",
  "colLocation": "Vị trí",
  "colModified": "Thời gian sửa đổi",
  "colSize": "Kích thước",
  "newDoc": "Tài liệu Docs AI",
  "newSheet": "Bảng tính Sheets AI",
  "newSlide": "Trình chiếu Slides AI",
  "newMarkdown": "Tài liệu Markdown AI",
  "newHtml": "Trang web HTML AI",
  "newPdf": "Tài liệu PDF AI",
  "openLocal": "Mở tệp cục bộ",
  "dropToOpenTitle": "Thả để mở tệp",
  "greetMorning": "Chào buổi sáng",
  "greetAfternoon": "Chào buổi chiều",
  "greetEvening": "Chào buổi tối",
  "greetAsk1": "Hôm nay bạn muốn tạo nội dung gì?",
  "greetAsk2": "Sẵn sàng bắt đầu chưa?",
  "greetAsk3": "Bạn muốn làm việc gì hôm nay?",
  "greetAsk4": "Bắt đầu từ đâu hôm nay?",
  "greetAsk5": "Bạn muốn tạo điều gì mới?",
  "greetAsk6": "Ý tưởng mới đã sẵn sàng chưa?",
  "filterAll": "Tất cả",
  "filterDocs": "Tài liệu",
  "filterSheets": "Bảng tính",
  "filterSlides": "Bản trình chiếu",
  "filterPdf": "PDF",
  "filterMd": "Markdown",
  "filterHtml": "HTML",
  "filterAria": "Lọc theo loại",
  "fileCount": "{n} tệp",
  "fileCountOne": "{n} tệp",
  "selectedCount": "Đã chọn {n} mục",
  "selectAll": "Chọn tất cả",
  "selectFile": "Chọn {name}",
  "removeFromList": "Xóa khỏi danh sách",
  "missingFileTitle": "Tệp không khả dụng",
  "missingFileBody": "Không thể tìm thấy “{name}” tại vị trí ban đầu. Tệp có thể đã bị di chuyển, đổi tên hoặc xóa.",
  "deleteFiles": "Xóa tệp",
  "cancel": "Hủy",
  "star": "Gắn dấu sao",
  "unstar": "Bỏ gắn dấu sao",
  "moreActions": "Thao tác khác",
  "open": "Mở",
  "revealInFolder": "Hiển thị trong thư mục",
  "copyPath": "Sao chép đường dẫn",
  "rename": "Đổi tên",
  "duplicate": "Tạo bản sao",
  "renameFailed": "Đổi tên thất bại",
  "emptyStarred": "Chưa có tệp gắn dấu sao — di chuột vào dòng và bấm biểu tượng ngôi sao.",
  "emptyRecent": "Chưa có tệp gần đây — tạo mới hoặc mở một tệp để bắt đầu.",
  "emptyFiltered": "Không có tệp nào thuộc định dạng này.",
  "folders": "Thư mục",
  "newFolder": "Thư mục mới",
  "newSubfolder": "Thư mục con mới",
  "untitledFolder": "Thư mục chưa đặt tên",
  "folderType": "Thư mục",
  "moveToFolder": "Di chuyển vào thư mục…",
  "moveToFolderTitle": "Di chuyển vào thư mục",
  "searchFolders": "Tìm kiếm thư mục",
  "searchFilesPlaceholder": "Tìm kiếm theo tên tệp và nội dung…",
  "searchIndexing": "Đang lập chỉ mục {n} tệp…",
  "searchNoResults": "Không có tệp nào khớp với “{q}”",
  "searchResultCount": "{n} kết quả",
  "searchResultCountOne": "{n} kết quả",
  "searchClear": "Xóa tìm kiếm",
  "noMatchingFolders": "Không có thư mục phù hợp.",
  "currentFolder": "Hiện tại",
  "moveCount": "Di chuyển {n}",
  "itemCount": "{n} mục",
  "itemCountOne": "{n} mục",
  "emptyFolder": "Thư mục này đang trống. Tạo một tệp mới hoặc kéo tệp vào đây.",
  "deleteFolder": "Xóa thư mục…",
  "deleteFolderTitle": "Xóa thư mục?",
  "deleteFolderConfirm": "“{name}” và tất cả nội dung bên trong sẽ được chuyển vào thùng rác.",
  "folderMoreActions": "Tác vụ khác cho {name}",
  "conflictTitle": "Một mục trùng tên đã tồn tại",
  "conflictBodyOne": "Thư mục đích đã có sẵn “{name}”. Bạn muốn xử lý như thế nào?",
  "conflictBodyMany": "Thư mục đích đã có sẵn {n} mục trùng tên. Bạn muốn xử lý như thế nào?",
  "conflictKeepBoth": "Giữ cả hai",
  "conflictReplace": "Thay thế",
  "rootUnusable": "Vị trí lưu mặc định không khả dụng nên không thể hiển thị thư mục.",
  "pickSaveDir": "Chọn một vị trí lưu",
  "deleteModalTitle": "Xóa tệp",
  "deleteConfirmOne": "Chuyển “{name}” vào Thùng rác?",
  "deleteConfirmMany": "Chuyển {n} tệp này vào Thùng rác?",
  "deleteMoreCount": "… tổng cộng {n} tệp",
  "delete": "Xóa",
  "timelineEmpty": "Dự án này chưa có cuộc trò chuyện AI nào.",
  "timelineYou": "Bạn",
  "timelineUserAria": "Người dùng",
  "untitled": "Chưa đặt tên",
  "noContent": "(trống)",
  "accountGenspark": "Tài khoản",
  "account": "Tài khoản",
  "login": "Đăng nhập",
  "loginGenspark": "Đăng nhập",
  "loggedIn": "Đã đăng nhập",
  "loggedInGenspark": "Đã đăng nhập",
  "waitingLogin": "Đang chờ đăng nhập từ trình duyệt… Bấm để mở lại trang đăng nhập",
  "loginTimeout": "Hết thời gian chờ đăng nhập — bấm để thử lại",
  "loginLaunchFailed": "Không thể bắt đầu đăng nhập — bấm để thử lại",
  "loginOpenManually": "Trình duyệt không tự mở? Bấm để mở thủ công",
  "loginOpenShort": "Mở trang đăng nhập thủ công",
  "loginCopyUrl": "Sao chép liên kết đăng nhập",
  "loginCopied": "Đã sao chép",
  "loginNetworkError": "Không thể kết nối đến máy chủ — kiểm tra lại mạng hoặc thiết lập proxy",
  "loginExpired": "Phiên đăng nhập đã hết hạn — bấm để thử lại",
  "loginFailed": "Đăng nhập thất bại — bấm để thử lại",
  "waitingShort": "Đang chờ…",
  "loggingOut": "Đang đăng xuất…",
  "logout": "Đăng xuất",
  "credits": "Hạn ngạch tín dụng",
  "creditsTip": "Xem chi tiết sử dụng tín dụng",
  "appVersion": "Phiên bản {v}",
  "versionLabel": "Phiên bản",
  "updateChannel": "Kênh cập nhật",
  "channelStable": "Bản ổn định",
  "channelBeta": "Bản thử nghiệm (Beta)",
  "theme": "Giao diện",
  "themeLight": "Sáng",
  "themeDark": "Tối",
  "themeSystem": "Theo hệ thống",
  "saveLocation": "Vị trí lưu",
  "setAutoSave": "Tự động lưu tất cả tài liệu",
  "setAutoSaveDesc": "Mặc định bật Tự động lưu trong mọi trình biên tập. Bạn vẫn có thể tắt riêng cho từng cửa sổ.",
  "setAnalytics": "Gửi số liệu thống kê sử dụng ẩn danh",
  "setAnalyticsDesc": "Mặc định bật và có thể tắt bất cứ lúc nào trong Cài đặt → Cài đặt chung. Sử dụng Google Analytics 4; Google nhận địa chỉ IP công khai và siêu dữ liệu truyền tải của bạn, tuyệt đối không bao giờ thu thập nội dung tài liệu hoặc tên tệp.",
  "setSearchRerank": "Xếp hạng lại tìm kiếm Jev",
  "setSearchRerankDesc": "Gửi trích đoạn của 20 kết quả hàng đầu cục bộ đến mô hình Jev của TypeSafe và sắp xếp lại theo mức độ liên quan. Mặc định tắt; khi bật, các trích đoạn sẽ được gửi ra ngoài thiết bị này.",
  "setSearchRerankEndpoint": "Điểm cuối Jev",
  "searchRerankedBy": "Đã sắp xếp lại theo mức độ liên quan bằng Jev",
  "searchJevSettings": "Xếp hạng lại ngữ nghĩa Jev",
  "setAiPanelSide": "Vị trí thanh bên AI",
  "aiPanelSideLeft": "Bên trái",
  "aiPanelSideRight": "Bên phải",
  "setAiFontSize": "Cỡ chữ khung AI",
  "aiFontSizeDefault": "Mặc định",
  "aiFontSizeLarge": "Lớn",
  "aiFontSizeXLarge": "Rất lớn",
  "aiFontSizeCustom": "Tùy chỉnh",
  "setAiSpellcheck": "Kiểm tra chính tả trong trò chuyện AI",
  "setDefaultApp": "Ứng dụng mặc định cho tài liệu Office",
  "setDefaultAppDesc": "Mở các tệp .docx, .xlsx và .pptx trong Xiao Office khi nhấp đúp.",
  "setDefaultAppIs": "Xiao Office hiện đã là ứng dụng mặc định.",
  "setDefaultAppOther": "Ứng dụng mặc định hiện tại: {app}",
  "setDefaultAppSet": "Đặt làm mặc định",
  "setDefaultAppOpenSettings": "Mở cài đặt hệ thống",
  "setDefaultAppFailed": "Không thể thay đổi. Vui lòng thiết lập thủ công trong Cài đặt hệ thống.",
  "setAiSpellcheckDesc": "Gạch chân các từ viết sai chính tả khi nhập tin nhắn trong khung trò chuyện AI.",
  "settings": "Cài đặt",
  "setSecAccount": "Tài khoản",
  "setSecGeneral": "Cài đặt chung",
  "setMcp": "Máy chủ MCP Cục bộ",
  "setMcpDesc": "Cho phép các tác tử AI bên ngoài (Claude Desktop, Cursor…) tạo tài liệu Word qua ứng dụng đang chạy. Chỉ chấp nhận kết nối từ localhost.",
  "setMcpPort": "Cổng (Port)",
  "setMcpRunning": "Đang chạy",
  "setMcpStopped": "Đã dừng",
  "setMcpConn": "Kết nối",
  "setMcpUrlHttp": "HTTP luồng dữ liệu (khuyến nghị)",
  "setMcpUrlSse": "SSE (cho các ứng dụng cũ)",
  "setMcpCopy": "Sao chép",
  "setMcpCopied": "Đã sao chép",
  "setMcpConfig": "Cấu hình ứng dụng máy khách mẫu",
  "setMcpConfigDesc": "Thêm đoạn cấu hình này vào cài đặt máy chủ MCP của ứng dụng (như mcp.json của Claude Desktop hoặc MCP settings của Cursor…).",
  "setMcpBg": "Tạo tệp trong nền",
  "setMcpBgDesc": "Ghi tài liệu trực tiếp vào đường dẫn tệp mà không cần mở giao diện; khi tắt, quá trình tạo sẽ hiển thị trực quan trong ứng dụng.",
  "setMcpLog": "Ghi nhật ký",
  "setMcpLogDesc": "Ghi lại hoạt động của máy chủ MCP và các công cụ vào tệp nhật ký cục bộ",
  "setMcpLogFile": "Tệp nhật ký",
  "setMcpLogOpen": "Mở",
  "setMcpLogClear": "Xóa sạch",
  "setMcpHealth": "Kiểm tra trạng thái",
  "setMcpLogRefresh": "Làm mới",
  "setMcpLogEmpty": "Chưa có mục nhật ký nào",
  "setSecAbout": "Giới thiệu",
  "setSecIntegrations": "Tích hợp",
  "intgHeroTitle": "Sử dụng Xiao Office từ trợ lý AI của bạn",
  "intgHeroDesc": "Sau khi kết nối, Claude Code, Codex, Cursor, Claude Desktop và các trợ lý tương tự có thể tạo, chuyển đổi, đọc và chỉnh sửa các tệp Word, Excel, PowerPoint, PDF và Markdown cho bạn. Mọi tác vụ đều xử lý trên máy tính này; không có dữ liệu nào bị tải lên ngoài.",
  "intgHeroStep1": "Chọn cách kết nối: CLI nếu trợ lý của bạn chạy được lệnh dòng lệnh, MCP nếu không hỗ trợ",
  "intgHeroStep2": "Làm theo hướng dẫn tương ứng bên dưới; thường chỉ cần một cú nhấp chuột",
  "intgHeroStep3": "Mở phiên trò chuyện mới và chỉ cần yêu cầu",
  "intgStep1Title": "Cài đặt kỹ năng (skill) vào trợ lý của bạn",
  "intgStep1Desc": "Chỉ hiển thị các trợ lý tìm thấy trên máy tính này. Hãy cài đặt vào trợ lý bạn thực sự sử dụng.",
  "intgStep1Update": "Khi có bản cập nhật kỹ năng mới từ Xiao Office, nút Cập nhật sẽ xuất hiện cạnh trợ lý.",
  "intgSkillVersion": "kỹ năng {v}",
  "intgStateMissing": "Chưa cài đặt kỹ năng",
  "intgStateInstalled": "Đã cài đặt kỹ năng {v} · sẵn sàng cho phiên trò chuyện tiếp theo",
  "intgOtherToggle": "Trợ lý của tôi không có trong danh sách",
  "intgOtherDesc": "Chọn một trong ba cách dưới đây để cài đặt kỹ năng.",
  "intgOtherFolderTitle": "Bất kỳ trợ lý nào đọc thư mục SKILL.md",
  "intgOtherFolderDesc": "Chọn thư mục skills của trợ lý và Xiao Office sẽ ghi tệp vào đó.",
  "intgOtherZipTitle": "Gửi tệp trực tiếp cho trợ lý",
  "intgOtherZipDesc": "Lưu kỹ năng thành tệp zip, sau đó yêu cầu trợ lý cài đặt.",
  "intgOtherNpxTitle": "Dùng lệnh skills (cần Node.js)",
  "intgOtherNpxDesc": "Chạy lệnh sau trong cửa sổ dòng lệnh:",
  "intgCopy": "Sao chép",
  "intgStep2Title": "Dùng thử ngay",
  "intgStep2Desc": "Mở phiên trò chuyện mới trong trợ lý của bạn và yêu cầu bằng câu lệnh thông thường, ví dụ:",
  "intgStep2DescBefore": "Sau khi cài đặt, hãy mở phiên trò chuyện mới trong trợ lý và yêu cầu bằng câu lệnh thông thường, ví dụ:",
  "intgExample1": "Chuyển ~/Downloads/report.md thành tài liệu Word",
  "intgExample2": "Tạo bài thuyết trình 6 trang về kết quả Quý 3",
  "intgExample3": "Chuyển budget.xlsx sang PDF và mở trong Xiao Office",
  "intgStep2Note": "Trợ lý sẽ tự động chạy dòng lệnh genoffice; bạn không bao giờ phải tự gõ lệnh.",
  "intgCliPartTitle": "CLI · dòng lệnh + kỹ năng",
  "intgCliPartDesc": "Dành cho các trợ lý hỗ trợ chạy lệnh dòng lệnh (Claude Code, Codex, Cursor...). Sau khi cài kỹ năng, trợ lý sẽ tự động gọi dòng lệnh genoffice để tạo, đọc và sửa tệp.",
  "intgMcpPartTitle": "MCP",
  "intgMcpPartDesc": "MCP là giao thức tiêu chuẩn giúp các trợ lý AI gọi các công cụ bên ngoài. Dùng khi trợ lý của bạn không chạy được lệnh hoặc khi bạn muốn điều khiển trực tiếp cửa sổ Xiao Office.",
  "intgMcpStdioTitle": "Được khởi chạy bởi trợ lý (khuyến nghị)",
  "intgMcpStdioDesc": "Trợ lý tự khởi chạy genoffice mcp: không cần bật tính năng nào ở đây, và Xiao Office không cần mở sẵn. Đầy đủ tính năng như CLI.",
  "intgMcpHttpTitle": "Máy chủ HTTP Cục bộ",
  "intgMcpHttpDesc": "Chạy bên trong Xiao Office; trợ lý kết nối qua URL và bạn có thể theo dõi trực quan từng bước tài liệu được xây dựng trong trình soạn thảo Word.",
  "intgMcpHttpAdvanced": "Nâng cao: các điểm cuối khác và nhật ký",
  "intgMcpTryNote": "Trợ lý giao tiếp với Xiao Office qua MCP; bạn không bao giờ phải nhập lệnh thủ công.",
  "intgMcpClaudeTitle": "Claude Code",
  "intgMcpClaudeDesc": "Chạy lệnh này một lần trong cửa sổ dòng lệnh:",
  "intgMcpOtherTitle": "Cursor, Claude Desktop hoặc bất kỳ trợ lý nào hỗ trợ MCP",
  "intgMcpOtherDesc": "Thêm đoạn này vào cài đặt máy chủ MCP của trợ lý (tệp JSON hoặc mục Thêm máy chủ MCP trong cài đặt):",
  "intgMcpNote": "Có thể thiết lập song song cả kỹ năng và MCP; trợ lý sẽ tự chọn một phương thức phù hợp.",
  "intgCliTitle": "Nâng cao: dòng lệnh genoffice",
  "intgCliReady": "genoffice {v} · đã sẵn sàng trong cửa sổ dòng lệnh ({path})",
  "intgCliNotOnPath": "genoffice {v} · chưa có trong PATH của dòng lệnh. Trợ lý vẫn tìm thấy qua ~/.genoffice/launcher, kỹ năng vẫn hoạt động bình thường. Để tự gõ lệnh genoffice, hãy chạy lệnh này một lần:",
  "intgCliLauncher": "Thư mục khởi chạy",
  "intgStateOutdated": "Đã cài {v}, có bản cập nhật lên {next}",
  "intgStateModified": "Đã cài {v} (đã sửa đổi)",
  "intgStateForeign": "Đã cài {v} (không phải do ứng dụng này cài)",
  "intgStateNewer": "Đã cài {v} (mới hơn phiên bản đi kèm)",
  "intgStateOccupied": "Thư mục đã được sử dụng",
  "intgInstall": "Cài đặt",
  "intgUpdate": "Cập nhật",
  "intgUninstall": "Gỡ cài đặt",
  "intgReinstall": "Cài đặt lại bản {v}",
  "intgOverwrite": "Ghi đè",
  "intgConfirm": "Xác nhận",
  "intgConfirmWrite": "Sẽ ghi vào: {path}",
  "intgConfirmRemove": "Sẽ xóa: {path}",
  "intgConfirmOverwriteModified": "Các chỉnh sửa của bạn trong tệp đó sẽ bị ghi đè.",
  "intgConfirmOverwriteOccupied": "Tệp SKILL.md hiện có trong thư mục đó sẽ được thay thế.",
  "intgInstalledHint": "Đã cài đặt. Có hiệu lực trong phiên làm việc mới.",
  "intgInstallElsewhere": "Cài đặt vào thư mục khác…",
  "intgPickDirTitle": "Chọn thư mục skills",
  "intgDownloadZip": "Tải xuống kỹ năng (zip)",
  "intgSaveZipTitle": "Lưu kỹ năng",
  "intgSavedTo": "Đã lưu vào {path}",
  "intgCopied": "Đã sao chép",
  "intgCliEphemeral": "Vui lòng kéo Xiao Office vào thư mục Applications trước, sau đó mới dùng dòng lệnh.",
  "intgCopyPath": "Sao chép đường dẫn",
  "intgCliNeedsUpdate": "Kỹ năng này cần dòng lệnh bản {v} hoặc mới hơn; vui lòng cập nhật Xiao Office.",
  "intgLoading": "Đang kiểm tra…",
  "intgUpdateDue": "Đã có bản cập nhật kỹ năng",
  "setSecAiModel": "Mô hình AI",
  "setAiProvider": "Nhà cung cấp",
  "setAiModelId": "Mô hình",
  "setAiApiKey": "Khóa API (API Key)",
  "setAiKeyHint": "Khóa được lưu trữ an toàn duy nhất trên thiết bị này.",
  "setAiBaseUrl": "Địa chỉ máy chủ (Base URL)",
  "setAiBaseUrlHint": "Để trống để dùng địa chỉ chính thức của nhà cung cấp.",
  "setAiGensparkHint": "Sử dụng tài khoản đám mây đã đăng nhập; không cần khóa API.",
  "setAiCodexPath": "Đường dẫn thực thi Codex",
  "setAiCodexPathHint": "Chỉ nhập khi bạn cài đặt tùy chỉnh; để trống để tự động nhận diện.",
  "setAiCodexAutoPlaceholder": "Tự động phát hiện (khuyến nghị)",
  "setAiCodexHint": "Tự động phát hiện và dùng CLI Codex đang đăng nhập sau các bản cập nhật; không cần khóa API.",
  "setAiByokNote": "Hội thoại dùng khóa API riêng của bạn. Tạo ảnh và phân tích phương tiện tuân theo mục AI Media; tìm kiếm web dùng nguồn miễn phí hoặc API do bạn cấu hình.",
  "setAiSave": "Lưu",
  "setAiSaved": "Đã lưu",
  "setAiTest": "Kiểm tra kết nối",
  "setAiTesting": "Đang kiểm tra kết nối…",
  "setAiTestOk": "Kết nối thành công",
  "setAiTestFail": "Kết nối thất bại",
  "setAiMaxTokens": "Giới hạn token xuất tối đa",
  "setAiMaxTokensDesc": "Ngân sách token cho một lượt phản hồi. Các mô hình suy luận (reasoning) sẽ dành một phần token để suy nghĩ; hãy tăng giá trị này nếu phản hồi bị ngắt quãng hoặc trả về trống.",
  "setSecAiMedia": "AI Hình ảnh, Phương tiện & Tìm kiếm",
  "setAiMediaGensparkHint": "Tạo hình ảnh và phân tích ảnh/video sử dụng dịch vụ đám mây.",
  "setAiImageModel": "Mô hình tạo ảnh",
  "setAiAnalysisModel": "Mô hình phân tích ảnh",
  "setAiSearchGensparkHint": "Tìm kiếm web và tìm kiếm hình ảnh qua các công cụ tìm kiếm hoặc nguồn miễn phí.",
  "setAiSearchSerperHint": "Serper cung cấp cả tìm kiếm web và hình ảnh bằng khóa API của bạn.",
  "setAiSearchTavilyHint": "Tavily cung cấp tìm kiếm web bằng khóa API của bạn; tìm kiếm ảnh dùng nguồn miễn phí.",
  "setAiSearchParallelHint": "Để trống khóa API để dùng tìm kiếm Parallel miễn phí (giới hạn lượt). Thêm khóa API để dùng tài khoản Parallel riêng của bạn.",
  "setAiCapImage": "Tạo hình ảnh",
  "setAiCapAnalysis": "Phân tích hình ảnh",
  "setAiCapVideo": "Phân tích video",
  "setAiCapSearch": "Tìm kiếm web",
  "setAiCapFileSearch": "Tìm kiếm tệp trên máy",
  "setAiSharedKeyHint": "Khóa API và Base URL của cùng một nhà cung cấp được dùng chung cho các năng lực; bạn chỉ cần nhập một lần.",
  "setAiGskTools": "Công cụ đám mây mở rộng",
  "setAiGskToolsDesc": "Tìm kiếm web, tạo ảnh và phân tích phương tiện chạy qua công cụ đám mây; khi tắt sẽ dùng nguồn miễn phí.",
  "setGithub": "Mã nguồn mở",
  "starOnGitHub": "Tặng sao trên GitHub",
  "starPromptTitle": "Bạn thích Xiao Office chứ?",
  "starPromptTitleN": "Bạn đã mở {n} tài liệu với Xiao Office",
  "starPromptBody": "Xiao Office hoàn toàn miễn phí và mã nguồn mở. Tặng một dấu sao (Star) trên GitHub là cách tốt nhất để ủng hộ đội ngũ phát triển!",
  "starPromptGo": "Tặng Star trên GitHub",
  "starPromptDone": "Đã tặng sao",
  "starPromptLater": "Để sau",
  "onbStarHint": "Nếu bạn yêu thích Xiao Office, hãy ủng hộ chúng tôi một ngôi sao trên GitHub nhé!",
  "setEmail": "Email",
  "setNotLoggedIn": "Chưa đăng nhập",
  "setViewUsage": "Xem mức sử dụng",
  "setChange": "Thay đổi",
  "today": "Hôm nay",
  "yesterday": "Hôm qua",
  "daysAgo": "{n} ngày trước",
  "language": "Ngôn ngữ",
  "closeTab": "Đóng thẻ",
  "tabList": "Tất cả các thẻ",
  "appMenu": "Trình đơn",
  "newTab": "Thẻ mới",
  "onbTitle1": "Chào mừng đến với Xiao Office",
  "onbSubtitle1": "Bộ ứng dụng văn phòng AI mã nguồn mở đầu tiên",
  "onbBody1": "Soạn thảo văn bản, lập bảng tính, thiết kế bài thuyết trình và xử lý PDF. Trợ lý AI đồng hành trong từng thao tác.",
  "onbTitle2": "Đây chỉ mới là khởi đầu",
  "onbBody2": "Xiao Office đang trong giai đoạn Alpha. Hãy tham gia nhóm thảo luận trên GenTeam để đóng góp ý kiến và định hình các tính năng tương lai.",
  "onbCredits": "Hỗ trợ các mô hình AI mạnh mẽ hàng đầu: Gemini, Claude, GPT, DeepSeek",
  "onbJoinGenTeam": "Tham gia GenTeam",
  "onbSkip": "Bỏ qua",
  "onbNext": "Tiếp theo",
  "onbStart": "Bắt đầu ngay",
  "onbStepAria": "Trang {n} / {total}",
  "onbTitle3": "Hoàn toàn miễn phí cho mọi người",
  "onbBody3": "Không phí bản quyền. Không quảng cáo. Không chèn hình mờ (watermark).",
  "onbNote3": "Các tính năng AI hoạt động mượt mà với khóa API hoặc mô hình cục bộ của bạn.",
  "onbBack": "Quay lại"
}
};
